version: "3.8"

services:
  # Product Service
  product-db:
    image: mariadb:10.5
    container_name: product-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_db
    ports:
      - "3307:3306"
    volumes:
      - product_data:/var/lib/mysql

  product-service:
    build: ./ProductService
    depends_on:
      - product-db
    ports:
      - "3001:3001"
    restart: unless-stopped

  # Order Service
  order-db:
    image: mariadb:10.5
    container_name: order-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_db
    ports:
      - "3308:3306"
    volumes:
      - order_data:/var/lib/mysql

  order-service:
    build: ./OrderService
    depends_on:
      - order-db
    ports:
      - "3002:3002"
    restart: unless-stopped

  # Customer Service
  customer-db:
    image: mariadb:10.5
    container_name: customer-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customer_db
    ports:
      - "3309:3306"
    volumes:
      - customer_data:/var/lib/mysql

  customer-service:
    build: ./CustomerService
    depends_on:
      - customer-db
    ports:
      - "3003:3003"
    restart: unless-stopped

  # API Gateway
  api-gateway:
    build: ./APIGateway
    ports:
      - "3000:3000"
    depends_on:
      - ProductService
      - OrderService
      - CustomerService
    restart: unless-stopped

volumes:
  product_data:
  order_data:
  customer_data:
